version: "2"
run:
  timeout: 1m
formatters:
  enable:
    - gofmt
    - goimports
linters:
  default: none
  exclusions:
    generated: lax
    paths:
      - data
      - search/align/matrix/matrix_test.go
      - seqhash/seqhash.go
    rules:
      - path: search/align/example_test.go
        linters:
          - nolintlint
  enable:
    - bodyclose
    - dupl
    - copyloopvar
    - gochecknoinits
    # - goconst # TODO: Enable this and fix the errors.
    - goprintffuncname
    - misspell
    - nakedret
    - nilnil
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
  settings:
    dupl:
      threshold: 500
    staticcheck:
      checks:
        - "ST*"
        - "-ST1005"