version: "2"
run:
  timeout: 1m
formatters:
  enable:
    - gofmt
    - goimports
linters:
  exclusions:
    paths:
      - data
  enable:
    - bodyclose
    - dupl
    - copyloopvar
    - gochecknoinits
    # - goconst # TODO: Enable this and fix the errors.
    - goprintffuncname
    - misspell
    - nakedret
    - nilnil
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1005"