version: "2"
run:
  timeout: 1m
issues:
  exclude-dirs:
    - data
formatters:
  enable:
    - gofmt
    - goimports
linters:
  enable:
    - bodyclose
    - dupl
    - copyloopvar
    - gochecknoinits
    # - goconst # TODO: Enable this and fix the errors.
    - goprintffuncname
    - misspell
    - nakedret
    - nilnil
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-ST1005"