run:
  timeout: 1m
  skip-dirs:
    - data
linters:
  enable:
    - bodyclose
    - dupl
    - exportloopref
    - gochecknoinits
    # - goconst # TODO: Enable this and fix the errors.
    - gofmt
    - goimports
    - goprintffuncname
    - misspell
    - nakedret
    - nilnil
    - noctx
    - nolintlint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  stylecheck:
    # https://staticcheck.io/docs/options#checks
    checks:
      - "all"
      - "-ST1005" # Disable "Incorrectly formatted error string" errors. TODO: Enable this and fix the errors.