package fold

var rnaComplement = map[byte]byte{'A': 'U', 'U': 'A', 'G': 'C', 'C': 'G', 'N': 'N'}

var rnaMultibranch = multibranchEnergies{2.5, 0.1, 0.4, 2.0}

var rnaNearestNeighbors = matchingBasepairEnergy{
	"AA/UU": {EnthalpyH: -6.8, EntropyS: -19},
	"AC/UG": {EnthalpyH: -11.4, EntropyS: -29.7},
	"AG/UC": {EnthalpyH: -10.5, EntropyS: -27.1},
	"AU/UA": {EnthalpyH: -9.4, EntropyS: -26.8},
	"CA/GU": {EnthalpyH: -10.4, EntropyS: -26.8},
	"CC/GG": {EnthalpyH: -13.4, EntropyS: -32.6},
	"CG/GC": {EnthalpyH: -10.6, EntropyS: -26.4},
	"CU/GA": {EnthalpyH: -10.5, EntropyS: -27.1},
	"GA/CU": {EnthalpyH: -12.4, EntropyS: -32.2},
	"GC/CG": {EnthalpyH: -14.9, EntropyS: -37.1},
	"GG/CC": {EnthalpyH: -13.4, EntropyS: -32.6},
	"GU/CA": {EnthalpyH: -11.4, EntropyS: -29.7},
	"UA/AU": {EnthalpyH: -7.7, EntropyS: -20.6},
	"UC/AG": {EnthalpyH: -12.4, EntropyS: -32.2},
	"UG/AC": {EnthalpyH: -10.4, EntropyS: -26.8},
	"UU/AA": {EnthalpyH: -6.8, EntropyS: -19},
}

var rnaInternalMismatches = matchingBasepairEnergy{
	"AA/AA": {EnthalpyH: 0, EntropyS: 0},
	"AA/AC": {EnthalpyH: 0, EntropyS: 0},
	"AA/AG": {EnthalpyH: 0, EntropyS: 0},
	"AA/AU": {EnthalpyH: 0, EntropyS: 0},
	"AA/CA": {EnthalpyH: 0, EntropyS: 0},
	"AA/CC": {EnthalpyH: 0, EntropyS: 0},
	"AA/CG": {EnthalpyH: 0, EntropyS: 0},
	"AA/CU": {EnthalpyH: 0, EntropyS: 0},
	"AA/GA": {EnthalpyH: 0, EntropyS: 0},
	"AA/GC": {EnthalpyH: 0, EntropyS: 0},
	"AA/GG": {EnthalpyH: 0, EntropyS: 0},
	"AA/GU": {EnthalpyH: 0, EntropyS: 0},
	"AA/UA": {EnthalpyH: 0, EntropyS: 0},
	"AA/UC": {EnthalpyH: 0, EntropyS: 0},
	"AA/UG": {EnthalpyH: 0, EntropyS: 0},
	"AC/AA": {EnthalpyH: 0, EntropyS: 0},
	"AC/AC": {EnthalpyH: 0, EntropyS: 0},
	"AC/AG": {EnthalpyH: 0, EntropyS: 0},
	"AC/AU": {EnthalpyH: 0, EntropyS: 0},
	"AC/CA": {EnthalpyH: 0, EntropyS: 0},
	"AC/CC": {EnthalpyH: 0, EntropyS: 0},
	"AC/CG": {EnthalpyH: 0, EntropyS: 0},
	"AC/CU": {EnthalpyH: 0, EntropyS: 0},
	"AC/GA": {EnthalpyH: 0, EntropyS: 0},
	"AC/GC": {EnthalpyH: 0, EntropyS: 0},
	"AC/GG": {EnthalpyH: 0, EntropyS: 0},
	"AC/GU": {EnthalpyH: 0, EntropyS: 0},
	"AC/UA": {EnthalpyH: 0, EntropyS: 0},
	"AC/UC": {EnthalpyH: 0, EntropyS: 0},
	"AC/UU": {EnthalpyH: 0, EntropyS: 0},
	"AG/AA": {EnthalpyH: 0, EntropyS: 0},
	"AG/AC": {EnthalpyH: 0, EntropyS: 0},
	"AG/AG": {EnthalpyH: 0, EntropyS: 0},
	"AG/AU": {EnthalpyH: 0, EntropyS: 0},
	"AG/CA": {EnthalpyH: 0, EntropyS: 0},
	"AG/CC": {EnthalpyH: 0, EntropyS: 0},
	"AG/CG": {EnthalpyH: 0, EntropyS: 0},
	"AG/CU": {EnthalpyH: 0, EntropyS: 0},
	"AG/GA": {EnthalpyH: 0, EntropyS: 0},
	"AG/GC": {EnthalpyH: 0, EntropyS: 0},
	"AG/GG": {EnthalpyH: 0, EntropyS: 0},
	"AG/GU": {EnthalpyH: 0, EntropyS: 0},
	"AG/UA": {EnthalpyH: 0, EntropyS: 0},
	"AG/UG": {EnthalpyH: 0, EntropyS: 0},
	"AG/UU": {EnthalpyH: -3.2, EntropyS: -8.4},
	"AU/AA": {EnthalpyH: 0, EntropyS: 0},
	"AU/AC": {EnthalpyH: 0, EntropyS: 0},
	"AU/AG": {EnthalpyH: 0, EntropyS: 0},
	"AU/AU": {EnthalpyH: 0, EntropyS: 0},
	"AU/CA": {EnthalpyH: 0, EntropyS: 0},
	"AU/CC": {EnthalpyH: 0, EntropyS: 0},
	"AU/CG": {EnthalpyH: 0, EntropyS: 0},
	"AU/CU": {EnthalpyH: 0, EntropyS: 0},
	"AU/GA": {EnthalpyH: 0, EntropyS: 0},
	"AU/GC": {EnthalpyH: 0, EntropyS: 0},
	"AU/GG": {EnthalpyH: 0, EntropyS: 0},
	"AU/GU": {EnthalpyH: 0, EntropyS: 0},
	"AU/UC": {EnthalpyH: 0, EntropyS: 0},
	"AU/UG": {EnthalpyH: -8.8, EntropyS: -23.9},
	"AU/UU": {EnthalpyH: 0, EntropyS: 0},
	"CA/AA": {EnthalpyH: 0, EntropyS: 0},
	"CA/AC": {EnthalpyH: 0, EntropyS: 0},
	"CA/AG": {EnthalpyH: 0, EntropyS: 0},
	"CA/AU": {EnthalpyH: 0, EntropyS: 0},
	"CA/CA": {EnthalpyH: 0, EntropyS: 0},
	"CA/CC": {EnthalpyH: 0, EntropyS: 0},
	"CA/CG": {EnthalpyH: 0, EntropyS: 0},
	"CA/CU": {EnthalpyH: 0, EntropyS: 0},
	"CA/GA": {EnthalpyH: 0, EntropyS: 0},
	"CA/GC": {EnthalpyH: 0, EntropyS: 0},
	"CA/GG": {EnthalpyH: 0, EntropyS: 0},
	"CA/UA": {EnthalpyH: 0, EntropyS: 0},
	"CA/UC": {EnthalpyH: 0, EntropyS: 0},
	"CA/UG": {EnthalpyH: 0, EntropyS: 0},
	"CA/UU": {EnthalpyH: 0, EntropyS: 0},
	"CC/AA": {EnthalpyH: 0, EntropyS: 0},
	"CC/AC": {EnthalpyH: 0, EntropyS: 0},
	"CC/AG": {EnthalpyH: 0, EntropyS: 0},
	"CC/AU": {EnthalpyH: 0, EntropyS: 0},
	"CC/CA": {EnthalpyH: 0, EntropyS: 0},
	"CC/CC": {EnthalpyH: 0, EntropyS: 0},
	"CC/CG": {EnthalpyH: 0, EntropyS: 0},
	"CC/CU": {EnthalpyH: 0, EntropyS: 0},
	"CC/GA": {EnthalpyH: 0, EntropyS: 0},
	"CC/GC": {EnthalpyH: 0, EntropyS: 0},
	"CC/GU": {EnthalpyH: 0, EntropyS: 0},
	"CC/UA": {EnthalpyH: 0, EntropyS: 0},
	"CC/UC": {EnthalpyH: 0, EntropyS: 0},
	"CC/UG": {EnthalpyH: 0, EntropyS: 0},
	"CC/UU": {EnthalpyH: 0, EntropyS: 0},
	"CG/AA": {EnthalpyH: 0, EntropyS: 0},
	"CG/AC": {EnthalpyH: 0, EntropyS: 0},
	"CG/AG": {EnthalpyH: 0, EntropyS: 0},
	"CG/AU": {EnthalpyH: 0, EntropyS: 0},
	"CG/CA": {EnthalpyH: 0, EntropyS: 0},
	"CG/CC": {EnthalpyH: 0, EntropyS: 0},
	"CG/CG": {EnthalpyH: 0, EntropyS: 0},
	"CG/CU": {EnthalpyH: 0, EntropyS: 0},
	"CG/GA": {EnthalpyH: 0, EntropyS: 0},
	"CG/GG": {EnthalpyH: 0, EntropyS: 0},
	"CG/GU": {EnthalpyH: -5.6, EntropyS: -13.5},
	"CG/UA": {EnthalpyH: 0, EntropyS: 0},
	"CG/UC": {EnthalpyH: 0, EntropyS: 0},
	"CG/UG": {EnthalpyH: 0, EntropyS: 0},
	"CG/UU": {EnthalpyH: 0, EntropyS: 0},
	"CU/AA": {EnthalpyH: 0, EntropyS: 0},
	"CU/AC": {EnthalpyH: 0, EntropyS: 0},
	"CU/AG": {EnthalpyH: 0, EntropyS: 0},
	"CU/AU": {EnthalpyH: 0, EntropyS: 0},
	"CU/CA": {EnthalpyH: 0, EntropyS: 0},
	"CU/CC": {EnthalpyH: 0, EntropyS: 0},
	"CU/CG": {EnthalpyH: 0, EntropyS: 0},
	"CU/CU": {EnthalpyH: 0, EntropyS: 0},
	"CU/GC": {EnthalpyH: 0, EntropyS: 0},
	"CU/GG": {EnthalpyH: -12.1, EntropyS: -32.2},
	"CU/GU": {EnthalpyH: 0, EntropyS: 0},
	"CU/UA": {EnthalpyH: 0, EntropyS: 0},
	"CU/UC": {EnthalpyH: 0, EntropyS: 0},
	"CU/UG": {EnthalpyH: 0, EntropyS: 0},
	"CU/UU": {EnthalpyH: 0, EntropyS: 0},
	"GA/AA": {EnthalpyH: 0, EntropyS: 0},
	"GA/AC": {EnthalpyH: 0, EntropyS: 0},
	"GA/AG": {EnthalpyH: 0, EntropyS: 0},
	"GA/AU": {EnthalpyH: 0, EntropyS: 0},
	"GA/CA": {EnthalpyH: 0, EntropyS: 0},
	"GA/CC": {EnthalpyH: 0, EntropyS: 0},
	"GA/CG": {EnthalpyH: 0, EntropyS: 0},
	"GA/GA": {EnthalpyH: 0, EntropyS: 0},
	"GA/GC": {EnthalpyH: 0, EntropyS: 0},
	"GA/GG": {EnthalpyH: 0, EntropyS: 0},
	"GA/GU": {EnthalpyH: 0, EntropyS: 0},
	"GA/UA": {EnthalpyH: 0, EntropyS: 0},
	"GA/UC": {EnthalpyH: 0, EntropyS: 0},
	"GA/UG": {EnthalpyH: 0, EntropyS: 0},
	"GA/UU": {EnthalpyH: -12.8, EntropyS: -37.1},
	"GC/AA": {EnthalpyH: 0, EntropyS: 0},
	"GC/AC": {EnthalpyH: 0, EntropyS: 0},
	"GC/AG": {EnthalpyH: 0, EntropyS: 0},
	"GC/AU": {EnthalpyH: 0, EntropyS: 0},
	"GC/CA": {EnthalpyH: 0, EntropyS: 0},
	"GC/CC": {EnthalpyH: 0, EntropyS: 0},
	"GC/CU": {EnthalpyH: 0, EntropyS: 0},
	"GC/GA": {EnthalpyH: 0, EntropyS: 0},
	"GC/GC": {EnthalpyH: 0, EntropyS: 0},
	"GC/GG": {EnthalpyH: 0, EntropyS: 0},
	"GC/GU": {EnthalpyH: 0, EntropyS: 0},
	"GC/UA": {EnthalpyH: 0, EntropyS: 0},
	"GC/UC": {EnthalpyH: 0, EntropyS: 0},
	"GC/UG": {EnthalpyH: -12.6, EntropyS: -32.6},
	"GC/UU": {EnthalpyH: 0, EntropyS: 0},
	"GG/AA": {EnthalpyH: 0, EntropyS: 0},
	"GG/AC": {EnthalpyH: 0, EntropyS: 0},
	"GG/AG": {EnthalpyH: 0, EntropyS: 0},
	"GG/AU": {EnthalpyH: 0, EntropyS: 0},
	"GG/CA": {EnthalpyH: 0, EntropyS: 0},
	"GG/CG": {EnthalpyH: 0, EntropyS: 0},
	"GG/CU": {EnthalpyH: -8.3, EntropyS: -21.9},
	"GG/GA": {EnthalpyH: 0, EntropyS: 0},
	"GG/GC": {EnthalpyH: 0, EntropyS: 0},
	"GG/GG": {EnthalpyH: 0, EntropyS: 0},
	"GG/GU": {EnthalpyH: 0, EntropyS: 0},
	"GG/UA": {EnthalpyH: 0, EntropyS: 0},
	"GG/UC": {EnthalpyH: -12.1, EntropyS: -32.2},
	"GG/UG": {EnthalpyH: 0, EntropyS: 0},
	"GG/UU": {EnthalpyH: -13.5, EntropyS: -41.9},
	"GU/AA": {EnthalpyH: 0, EntropyS: 0},
	"GU/AC": {EnthalpyH: 0, EntropyS: 0},
	"GU/AG": {EnthalpyH: 0, EntropyS: 0},
	"GU/AU": {EnthalpyH: 0, EntropyS: 0},
	"GU/CC": {EnthalpyH: 0, EntropyS: 0},
	"GU/CG": {EnthalpyH: -12.6, EntropyS: -32.6},
	"GU/CU": {EnthalpyH: 0, EntropyS: 0},
	"GU/GA": {EnthalpyH: 0, EntropyS: 0},
	"GU/GC": {EnthalpyH: 0, EntropyS: 0},
	"GU/GG": {EnthalpyH: 0, EntropyS: 0},
	"GU/GU": {EnthalpyH: 0, EntropyS: 0},
	"GU/UA": {EnthalpyH: -8.8, EntropyS: -23.9},
	"GU/UC": {EnthalpyH: 0, EntropyS: 0},
	"GU/UG": {EnthalpyH: -14.6, EntropyS: -51.3},
	"GU/UU": {EnthalpyH: 0, EntropyS: 0},
	"UA/AA": {EnthalpyH: 0, EntropyS: 0},
	"UA/AC": {EnthalpyH: 0, EntropyS: 0},
	"UA/AG": {EnthalpyH: 0, EntropyS: 0},
	"UA/CA": {EnthalpyH: 0, EntropyS: 0},
	"UA/CC": {EnthalpyH: 0, EntropyS: 0},
	"UA/CG": {EnthalpyH: 0, EntropyS: 0},
	"UA/CU": {EnthalpyH: 0, EntropyS: 0},
	"UA/GA": {EnthalpyH: 0, EntropyS: 0},
	"UA/GC": {EnthalpyH: 0, EntropyS: 0},
	"UA/GG": {EnthalpyH: 0, EntropyS: 0},
	"UA/GU": {EnthalpyH: -7, EntropyS: -19.3},
	"UA/UA": {EnthalpyH: 0, EntropyS: 0},
	"UA/UC": {EnthalpyH: 0, EntropyS: 0},
	"UA/UG": {EnthalpyH: 0, EntropyS: 0},
	"UA/UU": {EnthalpyH: 0, EntropyS: 0},
	"UC/AA": {EnthalpyH: 0, EntropyS: 0},
	"UC/AC": {EnthalpyH: 0, EntropyS: 0},
	"UC/AU": {EnthalpyH: 0, EntropyS: 0},
	"UC/CA": {EnthalpyH: 0, EntropyS: 0},
	"UC/CC": {EnthalpyH: 0, EntropyS: 0},
	"UC/CG": {EnthalpyH: 0, EntropyS: 0},
	"UC/CU": {EnthalpyH: 0, EntropyS: 0},
	"UC/GA": {EnthalpyH: 0, EntropyS: 0},
	"UC/GC": {EnthalpyH: 0, EntropyS: 0},
	"UC/GG": {EnthalpyH: -8.3, EntropyS: -21.9},
	"UC/GU": {EnthalpyH: 0, EntropyS: 0},
	"UC/UA": {EnthalpyH: 0, EntropyS: 0},
	"UC/UC": {EnthalpyH: 0, EntropyS: 0},
	"UC/UG": {EnthalpyH: 0, EntropyS: 0},
	"UC/UU": {EnthalpyH: 0, EntropyS: 0},
	"UG/AA": {EnthalpyH: 0, EntropyS: 0},
	"UG/AG": {EnthalpyH: 0, EntropyS: 0},
	"UG/AU": {EnthalpyH: -7, EntropyS: -19.3},
	"UG/CA": {EnthalpyH: 0, EntropyS: 0},
	"UG/CC": {EnthalpyH: 0, EntropyS: 0},
	"UG/CG": {EnthalpyH: 0, EntropyS: 0},
	"UG/CU": {EnthalpyH: 0, EntropyS: 0},
	"UG/GA": {EnthalpyH: 0, EntropyS: 0},
	"UG/GC": {EnthalpyH: -5.6, EntropyS: -13.5},
	"UG/GG": {EnthalpyH: 0, EntropyS: 0},
	"UG/GU": {EnthalpyH: -9.3, EntropyS: -31},
	"UG/UA": {EnthalpyH: 0, EntropyS: 0},
	"UG/UC": {EnthalpyH: 0, EntropyS: 0},
	"UG/UG": {EnthalpyH: 0, EntropyS: 0},
	"UG/UU": {EnthalpyH: 0, EntropyS: 0},
	"UU/AC": {EnthalpyH: 0, EntropyS: 0},
	"UU/AG": {EnthalpyH: -12.8, EntropyS: -37.1},
	"UU/AU": {EnthalpyH: 0, EntropyS: 0},
	"UU/CA": {EnthalpyH: 0, EntropyS: 0},
	"UU/CC": {EnthalpyH: 0, EntropyS: 0},
	"UU/CG": {EnthalpyH: 0, EntropyS: 0},
	"UU/CU": {EnthalpyH: 0, EntropyS: 0},
	"UU/GA": {EnthalpyH: -3.2, EntropyS: -8.4},
	"UU/GC": {EnthalpyH: 0, EntropyS: 0},
	"UU/GG": {EnthalpyH: -13.5, EntropyS: -41.9},
	"UU/GU": {EnthalpyH: 0, EntropyS: 0},
	"UU/UA": {EnthalpyH: 0, EntropyS: 0},
	"UU/UC": {EnthalpyH: 0, EntropyS: 0},
	"UU/UG": {EnthalpyH: 0, EntropyS: 0},
	"UU/UU": {EnthalpyH: 0, EntropyS: 0},
}

var rnaTerminalMismatches = matchingBasepairEnergy{
	"AA/AA": {EnthalpyH: 0, EntropyS: 0},
	"AA/AC": {EnthalpyH: 0, EntropyS: 0},
	"AA/AG": {EnthalpyH: 0, EntropyS: 0},
	"AA/AU": {EnthalpyH: 0, EntropyS: 0},
	"AA/CA": {EnthalpyH: 0, EntropyS: 0},
	"AA/CC": {EnthalpyH: 0, EntropyS: 0},
	"AA/CG": {EnthalpyH: 0, EntropyS: 0},
	"AA/CU": {EnthalpyH: 0, EntropyS: 0},
	"AA/GA": {EnthalpyH: 0, EntropyS: 0},
	"AA/GC": {EnthalpyH: 0, EntropyS: 0},
	"AA/GG": {EnthalpyH: 0, EntropyS: 0},
	"AA/GU": {EnthalpyH: 0, EntropyS: 0},
	"AA/UA": {EnthalpyH: -3.9, EntropyS: -10},
	"AA/UC": {EnthalpyH: 2, EntropyS: 9.7},
	"AA/UG": {EnthalpyH: -3.5, EntropyS: -8.7},
	"AA/UU": {EnthalpyH: 2, EntropyS: 9.7},
	"AC/AA": {EnthalpyH: 0, EntropyS: 0},
	"AC/AC": {EnthalpyH: 0, EntropyS: 0},
	"AC/AG": {EnthalpyH: 0, EntropyS: 0},
	"AC/AU": {EnthalpyH: 0, EntropyS: 0},
	"AC/CA": {EnthalpyH: 0, EntropyS: 0},
	"AC/CC": {EnthalpyH: 0, EntropyS: 0},
	"AC/CG": {EnthalpyH: 0, EntropyS: 0},
	"AC/CU": {EnthalpyH: 0, EntropyS: 0},
	"AC/GA": {EnthalpyH: 0, EntropyS: 0},
	"AC/GC": {EnthalpyH: 0, EntropyS: 0},
	"AC/GG": {EnthalpyH: 0, EntropyS: 0},
	"AC/GU": {EnthalpyH: 0, EntropyS: 0},
	"AC/UA": {EnthalpyH: -2.3, EntropyS: -5.5},
	"AC/UC": {EnthalpyH: 6, EntropyS: 21.6},
	"AC/UG": {EnthalpyH: -2.3, EntropyS: -5.5},
	"AC/UU": {EnthalpyH: -0.3, EntropyS: 1.3},
	"AG/AA": {EnthalpyH: 0, EntropyS: 0},
	"AG/AC": {EnthalpyH: 0, EntropyS: 0},
	"AG/AG": {EnthalpyH: 0, EntropyS: 0},
	"AG/AU": {EnthalpyH: 0, EntropyS: 0},
	"AG/CA": {EnthalpyH: 0, EntropyS: 0},
	"AG/CC": {EnthalpyH: 0, EntropyS: 0},
	"AG/CG": {EnthalpyH: 0, EntropyS: 0},
	"AG/CU": {EnthalpyH: 0, EntropyS: 0},
	"AG/GA": {EnthalpyH: 0, EntropyS: 0},
	"AG/GC": {EnthalpyH: 0, EntropyS: 0},
	"AG/GG": {EnthalpyH: 0, EntropyS: 0},
	"AG/GU": {EnthalpyH: 0, EntropyS: 0},
	"AG/UA": {EnthalpyH: -3.1, EntropyS: -7.4},
	"AG/UC": {EnthalpyH: 2, EntropyS: 9.7},
	"AG/UG": {EnthalpyH: -3.5, EntropyS: -8.7},
	"AG/UU": {EnthalpyH: 2, EntropyS: 9.7},
	"AU/AA": {EnthalpyH: 0, EntropyS: 0},
	"AU/AC": {EnthalpyH: 0, EntropyS: 0},
	"AU/AG": {EnthalpyH: 0, EntropyS: 0},
	"AU/AU": {EnthalpyH: 0, EntropyS: 0},
	"AU/CA": {EnthalpyH: 0, EntropyS: 0},
	"AU/CC": {EnthalpyH: 0, EntropyS: 0},
	"AU/CG": {EnthalpyH: 0, EntropyS: 0},
	"AU/CU": {EnthalpyH: 0, EntropyS: 0},
	"AU/GA": {EnthalpyH: 0, EntropyS: 0},
	"AU/GC": {EnthalpyH: 0, EntropyS: 0},
	"AU/GG": {EnthalpyH: 0, EntropyS: 0},
	"AU/GU": {EnthalpyH: 0, EntropyS: 0},
	"AU/UA": {EnthalpyH: -2.3, EntropyS: -5.5},
	"AU/UC": {EnthalpyH: 4.6, EntropyS: 17.4},
	"AU/UG": {EnthalpyH: -2.3, EntropyS: -5.5},
	"AU/UU": {EnthalpyH: -1.7, EntropyS: -2.9},
	"CA/AA": {EnthalpyH: 0, EntropyS: 0},
	"CA/AC": {EnthalpyH: 0, EntropyS: 0},
	"CA/AG": {EnthalpyH: 0, EntropyS: 0},
	"CA/AU": {EnthalpyH: 0, EntropyS: 0},
	"CA/CA": {EnthalpyH: 0, EntropyS: 0},
	"CA/CC": {EnthalpyH: 0, EntropyS: 0},
	"CA/CG": {EnthalpyH: 0, EntropyS: 0},
	"CA/CU": {EnthalpyH: 0, EntropyS: 0},
	"CA/GA": {EnthalpyH: -9.1, EntropyS: -24.5},
	"CA/GC": {EnthalpyH: -5.6, EntropyS: -13.2},
	"CA/GG": {EnthalpyH: -5.6, EntropyS: -13.5},
	"CA/GU": {EnthalpyH: -5.6, EntropyS: -13.2},
	"CA/UA": {EnthalpyH: 0, EntropyS: 0},
	"CA/UC": {EnthalpyH: 0, EntropyS: 0},
	"CA/UG": {EnthalpyH: 0, EntropyS: 0},
	"CA/UU": {EnthalpyH: 0, EntropyS: 0},
	"CC/AA": {EnthalpyH: 0, EntropyS: 0},
	"CC/AC": {EnthalpyH: 0, EntropyS: 0},
	"CC/AG": {EnthalpyH: 0, EntropyS: 0},
	"CC/AU": {EnthalpyH: 0, EntropyS: 0},
	"CC/CA": {EnthalpyH: 0, EntropyS: 0},
	"CC/CC": {EnthalpyH: 0, EntropyS: 0},
	"CC/CG": {EnthalpyH: 0, EntropyS: 0},
	"CC/CU": {EnthalpyH: 0, EntropyS: 0},
	"CC/GA": {EnthalpyH: -5.7, EntropyS: -15.2},
	"CC/GC": {EnthalpyH: -3.4, EntropyS: -7.4},
	"CC/GG": {EnthalpyH: -5.7, EntropyS: -15.2},
	"CC/GU": {EnthalpyH: -2.7, EntropyS: -6.1},
	"CC/UA": {EnthalpyH: 0, EntropyS: 0},
	"CC/UC": {EnthalpyH: 0, EntropyS: 0},
	"CC/UG": {EnthalpyH: 0, EntropyS: 0},
	"CC/UU": {EnthalpyH: 0, EntropyS: 0},
	"CG/AA": {EnthalpyH: 0, EntropyS: 0},
	"CG/AC": {EnthalpyH: 0, EntropyS: 0},
	"CG/AG": {EnthalpyH: 0, EntropyS: 0},
	"CG/AU": {EnthalpyH: 0, EntropyS: 0},
	"CG/CA": {EnthalpyH: 0, EntropyS: 0},
	"CG/CC": {EnthalpyH: 0, EntropyS: 0},
	"CG/CG": {EnthalpyH: 0, EntropyS: 0},
	"CG/CU": {EnthalpyH: 0, EntropyS: 0},
	"CG/GA": {EnthalpyH: -8.2, EntropyS: -21.9},
	"CG/GC": {EnthalpyH: -5.6, EntropyS: -13.2},
	"CG/GG": {EnthalpyH: -9.2, EntropyS: -24.5},
	"CG/GU": {EnthalpyH: -5.6, EntropyS: -13.2},
	"CG/UA": {EnthalpyH: 0, EntropyS: 0},
	"CG/UC": {EnthalpyH: 0, EntropyS: 0},
	"CG/UG": {EnthalpyH: 0, EntropyS: 0},
	"CG/UU": {EnthalpyH: 0, EntropyS: 0},
	"CU/AA": {EnthalpyH: 0, EntropyS: 0},
	"CU/AC": {EnthalpyH: 0, EntropyS: 0},
	"CU/AG": {EnthalpyH: 0, EntropyS: 0},
	"CU/AU": {EnthalpyH: 0, EntropyS: 0},
	"CU/CA": {EnthalpyH: 0, EntropyS: 0},
	"CU/CC": {EnthalpyH: 0, EntropyS: 0},
	"CU/CG": {EnthalpyH: 0, EntropyS: 0},
	"CU/CU": {EnthalpyH: 0, EntropyS: 0},
	"CU/GA": {EnthalpyH: -5.7, EntropyS: -15.2},
	"CU/GC": {EnthalpyH: -5.3, EntropyS: -12.6},
	"CU/GG": {EnthalpyH: -5.7, EntropyS: -15.2},
	"CU/GU": {EnthalpyH: -8.6, EntropyS: -23.9},
	"CU/UA": {EnthalpyH: 0, EntropyS: 0},
	"CU/UC": {EnthalpyH: 0, EntropyS: 0},
	"CU/UG": {EnthalpyH: 0, EntropyS: 0},
	"CU/UU": {EnthalpyH: 0, EntropyS: 0},
	"GA/AA": {EnthalpyH: 0, EntropyS: 0},
	"GA/AC": {EnthalpyH: 0, EntropyS: 0},
	"GA/AG": {EnthalpyH: 0, EntropyS: 0},
	"GA/AU": {EnthalpyH: 0, EntropyS: 0},
	"GA/CA": {EnthalpyH: -5.2, EntropyS: -13.2},
	"GA/CC": {EnthalpyH: -4, EntropyS: -8.1},
	"GA/CG": {EnthalpyH: -5.6, EntropyS: -13.9},
	"GA/CU": {EnthalpyH: -4, EntropyS: -8.1},
	"GA/GA": {EnthalpyH: 0, EntropyS: 0},
	"GA/GC": {EnthalpyH: 0, EntropyS: 0},
	"GA/GG": {EnthalpyH: 0, EntropyS: 0},
	"GA/GU": {EnthalpyH: 0, EntropyS: 0},
	"GA/UA": {EnthalpyH: -3.4, EntropyS: -10},
	"GA/UC": {EnthalpyH: 2, EntropyS: 9.7},
	"GA/UG": {EnthalpyH: -3.5, EntropyS: -8.7},
	"GA/UU": {EnthalpyH: 2, EntropyS: 9.7},
	"GC/AA": {EnthalpyH: 0, EntropyS: 0},
	"GC/AC": {EnthalpyH: 0, EntropyS: 0},
	"GC/AG": {EnthalpyH: 0, EntropyS: 0},
	"GC/AU": {EnthalpyH: 0, EntropyS: 0},
	"GC/CA": {EnthalpyH: -7.2, EntropyS: -19.7},
	"GC/CC": {EnthalpyH: 0.5, EntropyS: 3.9},
	"GC/CG": {EnthalpyH: -7.2, EntropyS: -19.7},
	"GC/CU": {EnthalpyH: -4.2, EntropyS: -11.9},
	"GC/GA": {EnthalpyH: 0, EntropyS: 0},
	"GC/GC": {EnthalpyH: 0, EntropyS: 0},
	"GC/GG": {EnthalpyH: 0, EntropyS: 0},
	"GC/GU": {EnthalpyH: 0, EntropyS: 0},
	"GC/UA": {EnthalpyH: -2.3, EntropyS: -5.5},
	"GC/UC": {EnthalpyH: 6, EntropyS: 21.6},
	"GC/UG": {EnthalpyH: -2.3, EntropyS: -5.5},
	"GC/UU": {EnthalpyH: -0.3, EntropyS: 1.3},
	"GG/AA": {EnthalpyH: 0, EntropyS: 0},
	"GG/AC": {EnthalpyH: 0, EntropyS: 0},
	"GG/AG": {EnthalpyH: 0, EntropyS: 0},
	"GG/AU": {EnthalpyH: 0, EntropyS: 0},
	"GG/CA": {EnthalpyH: -7.1, EntropyS: -17.7},
	"GG/CC": {EnthalpyH: -4, EntropyS: -8.1},
	"GG/CG": {EnthalpyH: -6.2, EntropyS: -15.5},
	"GG/CU": {EnthalpyH: -4, EntropyS: -8.1},
	"GG/GA": {EnthalpyH: 0, EntropyS: 0},
	"GG/GC": {EnthalpyH: 0, EntropyS: 0},
	"GG/GG": {EnthalpyH: 0, EntropyS: 0},
	"GG/GU": {EnthalpyH: 0, EntropyS: 0},
	"GG/UA": {EnthalpyH: -0.6, EntropyS: 0},
	"GG/UC": {EnthalpyH: 2, EntropyS: 9.7},
	"GG/UG": {EnthalpyH: -3.5, EntropyS: -8.7},
	"GG/UU": {EnthalpyH: 2, EntropyS: 9.7},
	"GU/AA": {EnthalpyH: 0, EntropyS: 0},
	"GU/AC": {EnthalpyH: 0, EntropyS: 0},
	"GU/AG": {EnthalpyH: 0, EntropyS: 0},
	"GU/AU": {EnthalpyH: 0, EntropyS: 0},
	"GU/CA": {EnthalpyH: -7.2, EntropyS: -19.7},
	"GU/CC": {EnthalpyH: -0.3, EntropyS: 2.3},
	"GU/CG": {EnthalpyH: -7.2, EntropyS: -19.7},
	"GU/CU": {EnthalpyH: -5, EntropyS: -13.9},
	"GU/GA": {EnthalpyH: 0, EntropyS: 0},
	"GU/GC": {EnthalpyH: 0, EntropyS: 0},
	"GU/GG": {EnthalpyH: 0, EntropyS: 0},
	"GU/GU": {EnthalpyH: 0, EntropyS: 0},
	"GU/UA": {EnthalpyH: -2.3, EntropyS: -5.5},
	"GU/UC": {EnthalpyH: 4.6, EntropyS: 17.4},
	"GU/UG": {EnthalpyH: -2.3, EntropyS: -5.5},
	"GU/UU": {EnthalpyH: 1.6, EntropyS: 7.1},
	"UA/AA": {EnthalpyH: -4, EntropyS: -9.7},
	"UA/AC": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UA/AG": {EnthalpyH: -8.9, EntropyS: -25.1},
	"UA/AU": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UA/CA": {EnthalpyH: 0, EntropyS: 0},
	"UA/CC": {EnthalpyH: 0, EntropyS: 0},
	"UA/CG": {EnthalpyH: 0, EntropyS: 0},
	"UA/CU": {EnthalpyH: 0, EntropyS: 0},
	"UA/GA": {EnthalpyH: -4.8, EntropyS: -12.3},
	"UA/GC": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UA/GG": {EnthalpyH: -8.9, EntropyS: -25.1},
	"UA/GU": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UA/UA": {EnthalpyH: 0, EntropyS: 0},
	"UA/UC": {EnthalpyH: 0, EntropyS: 0},
	"UA/UG": {EnthalpyH: 0, EntropyS: 0},
	"UA/UU": {EnthalpyH: 0, EntropyS: 0},
	"UC/AA": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UC/AC": {EnthalpyH: -5.1, EntropyS: -14.5},
	"UC/AG": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UC/AU": {EnthalpyH: -1.8, EntropyS: -4.2},
	"UC/CA": {EnthalpyH: 0, EntropyS: 0},
	"UC/CC": {EnthalpyH: 0, EntropyS: 0},
	"UC/CG": {EnthalpyH: 0, EntropyS: 0},
	"UC/CU": {EnthalpyH: 0, EntropyS: 0},
	"UC/GA": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UC/GC": {EnthalpyH: -5.1, EntropyS: -14.5},
	"UC/GG": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UC/GU": {EnthalpyH: -1.8, EntropyS: -4.2},
	"UC/UA": {EnthalpyH: 0, EntropyS: 0},
	"UC/UC": {EnthalpyH: 0, EntropyS: 0},
	"UC/UG": {EnthalpyH: 0, EntropyS: 0},
	"UC/UU": {EnthalpyH: 0, EntropyS: 0},
	"UG/AA": {EnthalpyH: -3.8, EntropyS: -8.7},
	"UG/AC": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UG/AG": {EnthalpyH: -8.9, EntropyS: -24.8},
	"UG/AU": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UG/CA": {EnthalpyH: 0, EntropyS: 0},
	"UG/CC": {EnthalpyH: 0, EntropyS: 0},
	"UG/CG": {EnthalpyH: 0, EntropyS: 0},
	"UG/CU": {EnthalpyH: 0, EntropyS: 0},
	"UG/GA": {EnthalpyH: 3.1, EntropyS: 11.6},
	"UG/GC": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UG/GG": {EnthalpyH: -1.5, EntropyS: -2.3},
	"UG/GU": {EnthalpyH: -6.3, EntropyS: -17.7},
	"UG/UA": {EnthalpyH: 0, EntropyS: 0},
	"UG/UC": {EnthalpyH: 0, EntropyS: 0},
	"UG/UG": {EnthalpyH: 0, EntropyS: 0},
	"UG/UU": {EnthalpyH: 0, EntropyS: 0},
	"UU/AA": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UU/AC": {EnthalpyH: -1.4, EntropyS: -2.6},
	"UU/AG": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UU/AU": {EnthalpyH: 1.4, EntropyS: 6.1},
	"UU/CA": {EnthalpyH: 0, EntropyS: 0},
	"UU/CC": {EnthalpyH: 0, EntropyS: 0},
	"UU/CG": {EnthalpyH: 0, EntropyS: 0},
	"UU/CU": {EnthalpyH: 0, EntropyS: 0},
	"UU/GA": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UU/GC": {EnthalpyH: -1.4, EntropyS: -2.6},
	"UU/GG": {EnthalpyH: -4.3, EntropyS: -11.6},
	"UU/GU": {EnthalpyH: 1.4, EntropyS: 6.1},
	"UU/UA": {EnthalpyH: 0, EntropyS: 0},
	"UU/UC": {EnthalpyH: 0, EntropyS: 0},
	"UU/UG": {EnthalpyH: 0, EntropyS: 0},
	"UU/UU": {EnthalpyH: 0, EntropyS: 0},
}

var rnaDanglingEnds = matchingBasepairEnergy{
	".A/AA": {EnthalpyH: 0, EntropyS: 0},
	".A/AC": {EnthalpyH: 0, EntropyS: 0},
	".A/AG": {EnthalpyH: 0, EntropyS: 0},
	".A/AU": {EnthalpyH: -5.7, EntropyS: -16.1},
	".A/CA": {EnthalpyH: 0, EntropyS: 0},
	".A/CC": {EnthalpyH: 0, EntropyS: 0},
	".A/CG": {EnthalpyH: 0, EntropyS: 0},
	".A/CU": {EnthalpyH: -0.7, EntropyS: -1.9},
	".A/GA": {EnthalpyH: 0, EntropyS: 0},
	".A/GC": {EnthalpyH: 0, EntropyS: 0},
	".A/GG": {EnthalpyH: 0, EntropyS: 0},
	".A/GU": {EnthalpyH: -5.8, EntropyS: -16.4},
	".A/UA": {EnthalpyH: 0, EntropyS: 0},
	".A/UC": {EnthalpyH: 0, EntropyS: 0},
	".A/UG": {EnthalpyH: 0, EntropyS: 0},
	".A/UU": {EnthalpyH: -2.2, EntropyS: -6.8},
	".C/AA": {EnthalpyH: 0, EntropyS: 0},
	".C/AC": {EnthalpyH: 0, EntropyS: 0},
	".C/AG": {EnthalpyH: -7.4, EntropyS: -20.3},
	".C/AU": {EnthalpyH: 0, EntropyS: 0},
	".C/CA": {EnthalpyH: 0, EntropyS: 0},
	".C/CC": {EnthalpyH: 0, EntropyS: 0},
	".C/CG": {EnthalpyH: -2.8, EntropyS: -7.7},
	".C/CU": {EnthalpyH: 0, EntropyS: 0},
	".C/GA": {EnthalpyH: 0, EntropyS: 0},
	".C/GC": {EnthalpyH: 0, EntropyS: 0},
	".C/GG": {EnthalpyH: -6.4, EntropyS: -16.4},
	".C/GU": {EnthalpyH: 0, EntropyS: 0},
	".C/UA": {EnthalpyH: 0, EntropyS: 0},
	".C/UC": {EnthalpyH: 0, EntropyS: 0},
	".C/UG": {EnthalpyH: -3.6, EntropyS: -9.7},
	".C/UU": {EnthalpyH: 0, EntropyS: 0},
	".G/AA": {EnthalpyH: 0, EntropyS: 0},
	".G/AC": {EnthalpyH: -9, EntropyS: -23.5},
	".G/AG": {EnthalpyH: 0, EntropyS: 0},
	".G/AU": {EnthalpyH: -5.7, EntropyS: -16.1},
	".G/CA": {EnthalpyH: 0, EntropyS: 0},
	".G/CC": {EnthalpyH: -4.1, EntropyS: -10.6},
	".G/CG": {EnthalpyH: 0, EntropyS: 0},
	".G/CU": {EnthalpyH: -0.7, EntropyS: -1.9},
	".G/GA": {EnthalpyH: 0, EntropyS: 0},
	".G/GC": {EnthalpyH: -8.6, EntropyS: -22.2},
	".G/GG": {EnthalpyH: 0, EntropyS: 0},
	".G/GU": {EnthalpyH: -5.8, EntropyS: -16.4},
	".G/UA": {EnthalpyH: 0, EntropyS: 0},
	".G/UC": {EnthalpyH: -7.5, EntropyS: -20.3},
	".G/UG": {EnthalpyH: 0, EntropyS: 0},
	".G/UU": {EnthalpyH: -2.2, EntropyS: -6.8},
	".U/AA": {EnthalpyH: -4.9, EntropyS: -13.2},
	".U/AC": {EnthalpyH: 0, EntropyS: 0},
	".U/AG": {EnthalpyH: -4.9, EntropyS: -13.2},
	".U/AU": {EnthalpyH: 0, EntropyS: 0},
	".U/CA": {EnthalpyH: -0.9, EntropyS: -1.3},
	".U/CC": {EnthalpyH: 0, EntropyS: 0},
	".U/CG": {EnthalpyH: -0.9, EntropyS: -1.3},
	".U/CU": {EnthalpyH: 0, EntropyS: 0},
	".U/GA": {EnthalpyH: -5.5, EntropyS: -15.2},
	".U/GC": {EnthalpyH: 0, EntropyS: 0},
	".U/GG": {EnthalpyH: -5.5, EntropyS: -15.2},
	".U/GU": {EnthalpyH: 0, EntropyS: 0},
	".U/UA": {EnthalpyH: -2.3, EntropyS: -5.5},
	".U/UC": {EnthalpyH: 0, EntropyS: 0},
	".U/UG": {EnthalpyH: -2.3, EntropyS: -5.5},
	".U/UU": {EnthalpyH: 0, EntropyS: 0},
	"A./AA": {EnthalpyH: 0, EntropyS: 0},
	"A./AC": {EnthalpyH: 0, EntropyS: 0},
	"A./AG": {EnthalpyH: 0, EntropyS: 0},
	"A./AU": {EnthalpyH: 0, EntropyS: 0},
	"A./CA": {EnthalpyH: 0, EntropyS: 0},
	"A./CC": {EnthalpyH: 0, EntropyS: 0},
	"A./CG": {EnthalpyH: 0, EntropyS: 0},
	"A./CU": {EnthalpyH: 0, EntropyS: 0},
	"A./GA": {EnthalpyH: 0, EntropyS: 0},
	"A./GC": {EnthalpyH: 0, EntropyS: 0},
	"A./GG": {EnthalpyH: 0, EntropyS: 0},
	"A./GU": {EnthalpyH: 0, EntropyS: 0},
	"A./UA": {EnthalpyH: -0.5, EntropyS: -0.6},
	"A./UC": {EnthalpyH: 6.9, EntropyS: 22.6},
	"A./UG": {EnthalpyH: 0.6, EntropyS: 2.6},
	"A./UU": {EnthalpyH: 0.6, EntropyS: 2.6},
	"AA/.A": {EnthalpyH: 0, EntropyS: 0},
	"AA/.C": {EnthalpyH: 0, EntropyS: 0},
	"AA/.G": {EnthalpyH: 0, EntropyS: 0},
	"AA/.U": {EnthalpyH: 1.6, EntropyS: 6.1},
	"AA/A.": {EnthalpyH: 0, EntropyS: 0},
	"AA/C.": {EnthalpyH: 0, EntropyS: 0},
	"AA/G.": {EnthalpyH: 0, EntropyS: 0},
	"AA/U.": {EnthalpyH: -4.9, EntropyS: -13.2},
	"AC/.A": {EnthalpyH: 0, EntropyS: 0},
	"AC/.C": {EnthalpyH: 0, EntropyS: 0},
	"AC/.G": {EnthalpyH: -2.4, EntropyS: -6.1},
	"AC/.U": {EnthalpyH: 0, EntropyS: 0},
	"AC/A.": {EnthalpyH: 0, EntropyS: 0},
	"AC/C.": {EnthalpyH: 0, EntropyS: 0},
	"AC/G.": {EnthalpyH: 0, EntropyS: 0},
	"AC/U.": {EnthalpyH: -0.9, EntropyS: -1.3},
	"AG/.A": {EnthalpyH: 0, EntropyS: 0},
	"AG/.C": {EnthalpyH: -1.6, EntropyS: -4.5},
	"AG/.G": {EnthalpyH: 0, EntropyS: 0},
	"AG/.U": {EnthalpyH: 1.6, EntropyS: 6.1},
	"AG/A.": {EnthalpyH: 0, EntropyS: 0},
	"AG/C.": {EnthalpyH: 0, EntropyS: 0},
	"AG/G.": {EnthalpyH: 0, EntropyS: 0},
	"AG/U.": {EnthalpyH: -5.5, EntropyS: -15.2},
	"AU/.A": {EnthalpyH: -0.5, EntropyS: -0.6},
	"AU/.C": {EnthalpyH: 0, EntropyS: 0},
	"AU/.G": {EnthalpyH: -0.5, EntropyS: -0.6},
	"AU/.U": {EnthalpyH: 0, EntropyS: 0},
	"AU/A.": {EnthalpyH: 0, EntropyS: 0},
	"AU/C.": {EnthalpyH: 0, EntropyS: 0},
	"AU/G.": {EnthalpyH: 0, EntropyS: 0},
	"AU/U.": {EnthalpyH: -2.3, EntropyS: -5.5},
	"C./AA": {EnthalpyH: 0, EntropyS: 0},
	"C./AC": {EnthalpyH: 0, EntropyS: 0},
	"C./AG": {EnthalpyH: 0, EntropyS: 0},
	"C./AU": {EnthalpyH: 0, EntropyS: 0},
	"C./CA": {EnthalpyH: 0, EntropyS: 0},
	"C./CC": {EnthalpyH: 0, EntropyS: 0},
	"C./CG": {EnthalpyH: 0, EntropyS: 0},
	"C./CU": {EnthalpyH: 0, EntropyS: 0},
	"C./GA": {EnthalpyH: -1.6, EntropyS: -4.5},
	"C./GC": {EnthalpyH: 0.7, EntropyS: 3.2},
	"C./GG": {EnthalpyH: -4.6, EntropyS: -14.8},
	"C./GU": {EnthalpyH: -0.4, EntropyS: -1.3},
	"C./UA": {EnthalpyH: 0, EntropyS: 0},
	"C./UC": {EnthalpyH: 0, EntropyS: 0},
	"C./UG": {EnthalpyH: 0, EntropyS: 0},
	"C./UU": {EnthalpyH: 0, EntropyS: 0},
	"CA/.A": {EnthalpyH: 0, EntropyS: 0},
	"CA/.C": {EnthalpyH: 0, EntropyS: 0},
	"CA/.G": {EnthalpyH: 0, EntropyS: 0},
	"CA/.U": {EnthalpyH: 2.2, EntropyS: 8.1},
	"CA/A.": {EnthalpyH: 0, EntropyS: 0},
	"CA/C.": {EnthalpyH: 0, EntropyS: 0},
	"CA/G.": {EnthalpyH: -9, EntropyS: -23.5},
	"CA/U.": {EnthalpyH: 0, EntropyS: 0},
	"CC/.A": {EnthalpyH: 0, EntropyS: 0},
	"CC/.C": {EnthalpyH: 0, EntropyS: 0},
	"CC/.G": {EnthalpyH: 3.3, EntropyS: 11.6},
	"CC/.U": {EnthalpyH: 0, EntropyS: 0},
	"CC/A.": {EnthalpyH: 0, EntropyS: 0},
	"CC/C.": {EnthalpyH: 0, EntropyS: 0},
	"CC/G.": {EnthalpyH: -4.1, EntropyS: -10.6},
	"CC/U.": {EnthalpyH: 0, EntropyS: 0},
	"CG/.A": {EnthalpyH: 0, EntropyS: 0},
	"CG/.C": {EnthalpyH: 0.7, EntropyS: 3.2},
	"CG/.G": {EnthalpyH: 0, EntropyS: 0},
	"CG/.U": {EnthalpyH: 2.2, EntropyS: 8.1},
	"CG/A.": {EnthalpyH: 0, EntropyS: 0},
	"CG/C.": {EnthalpyH: 0, EntropyS: 0},
	"CG/G.": {EnthalpyH: -8.6, EntropyS: -22.2},
	"CG/U.": {EnthalpyH: 0, EntropyS: 0},
	"CU/.A": {EnthalpyH: 6.9, EntropyS: 22.6},
	"CU/.C": {EnthalpyH: 0, EntropyS: 0},
	"CU/.G": {EnthalpyH: 6.9, EntropyS: 22.6},
	"CU/.U": {EnthalpyH: 0, EntropyS: 0},
	"CU/A.": {EnthalpyH: 0, EntropyS: 0},
	"CU/C.": {EnthalpyH: 0, EntropyS: 0},
	"CU/G.": {EnthalpyH: -7.5, EntropyS: -20.3},
	"CU/U.": {EnthalpyH: 0, EntropyS: 0},
	"G./AA": {EnthalpyH: 0, EntropyS: 0},
	"G./AC": {EnthalpyH: 0, EntropyS: 0},
	"G./AG": {EnthalpyH: 0, EntropyS: 0},
	"G./AU": {EnthalpyH: 0, EntropyS: 0},
	"G./CA": {EnthalpyH: -2.4, EntropyS: -6.1},
	"G./CC": {EnthalpyH: 3.3, EntropyS: 11.6},
	"G./CG": {EnthalpyH: 0.8, EntropyS: 3.2},
	"G./CU": {EnthalpyH: -1.4, EntropyS: -4.2},
	"G./GA": {EnthalpyH: 0, EntropyS: 0},
	"G./GC": {EnthalpyH: 0, EntropyS: 0},
	"G./GG": {EnthalpyH: 0, EntropyS: 0},
	"G./GU": {EnthalpyH: 0, EntropyS: 0},
	"G./UA": {EnthalpyH: -0.5, EntropyS: -0.6},
	"G./UC": {EnthalpyH: 6.9, EntropyS: 22.6},
	"G./UG": {EnthalpyH: 0.6, EntropyS: 2.6},
	"G./UU": {EnthalpyH: 0.6, EntropyS: 2.6},
	"GA/.A": {EnthalpyH: 0, EntropyS: 0},
	"GA/.C": {EnthalpyH: 0, EntropyS: 0},
	"GA/.G": {EnthalpyH: 0, EntropyS: 0},
	"GA/.U": {EnthalpyH: 0.7, EntropyS: 3.5},
	"GA/A.": {EnthalpyH: 0, EntropyS: 0},
	"GA/C.": {EnthalpyH: -7.4, EntropyS: -20.3},
	"GA/G.": {EnthalpyH: 0, EntropyS: 0},
	"GA/U.": {EnthalpyH: -4.9, EntropyS: -13.2},
	"GC/.A": {EnthalpyH: 0, EntropyS: 0},
	"GC/.C": {EnthalpyH: 0, EntropyS: 0},
	"GC/.G": {EnthalpyH: 0.8, EntropyS: 3.2},
	"GC/.U": {EnthalpyH: 0, EntropyS: 0},
	"GC/A.": {EnthalpyH: 0, EntropyS: 0},
	"GC/C.": {EnthalpyH: -2.8, EntropyS: -7.7},
	"GC/G.": {EnthalpyH: 0, EntropyS: 0},
	"GC/U.": {EnthalpyH: -0.9, EntropyS: -1.3},
	"GG/.A": {EnthalpyH: 0, EntropyS: 0},
	"GG/.C": {EnthalpyH: -4.6, EntropyS: -14.8},
	"GG/.G": {EnthalpyH: 0, EntropyS: 0},
	"GG/.U": {EnthalpyH: 0.7, EntropyS: 3.5},
	"GG/A.": {EnthalpyH: 0, EntropyS: 0},
	"GG/C.": {EnthalpyH: -6.4, EntropyS: -16.4},
	"GG/G.": {EnthalpyH: 0, EntropyS: 0},
	"GG/U.": {EnthalpyH: -5.5, EntropyS: -15.2},
	"GU/.A": {EnthalpyH: 0.6, EntropyS: 2.6},
	"GU/.C": {EnthalpyH: 0, EntropyS: 0},
	"GU/.G": {EnthalpyH: 0.6, EntropyS: 2.6},
	"GU/.U": {EnthalpyH: 0, EntropyS: 0},
	"GU/A.": {EnthalpyH: 0, EntropyS: 0},
	"GU/C.": {EnthalpyH: -3.6, EntropyS: -9.7},
	"GU/G.": {EnthalpyH: 0, EntropyS: 0},
	"GU/U.": {EnthalpyH: -2.3, EntropyS: -5.5},
	"U./AA": {EnthalpyH: 1.6, EntropyS: 6.1},
	"U./AC": {EnthalpyH: 2.2, EntropyS: 8.1},
	"U./AG": {EnthalpyH: 0.7, EntropyS: 3.5},
	"U./AU": {EnthalpyH: 3.1, EntropyS: 10.6},
	"U./CA": {EnthalpyH: 0, EntropyS: 0},
	"U./CC": {EnthalpyH: 0, EntropyS: 0},
	"U./CG": {EnthalpyH: 0, EntropyS: 0},
	"U./CU": {EnthalpyH: 0, EntropyS: 0},
	"U./GA": {EnthalpyH: 1.6, EntropyS: 6.1},
	"U./GC": {EnthalpyH: 2.2, EntropyS: 8.1},
	"U./GG": {EnthalpyH: 0.7, EntropyS: 3.5},
	"U./GU": {EnthalpyH: 3.1, EntropyS: 10.6},
	"U./UA": {EnthalpyH: 0, EntropyS: 0},
	"U./UC": {EnthalpyH: 0, EntropyS: 0},
	"U./UG": {EnthalpyH: 0, EntropyS: 0},
	"U./UU": {EnthalpyH: 0, EntropyS: 0},
	"UA/.A": {EnthalpyH: 0, EntropyS: 0},
	"UA/.C": {EnthalpyH: 0, EntropyS: 0},
	"UA/.G": {EnthalpyH: 0, EntropyS: 0},
	"UA/.U": {EnthalpyH: 3.1, EntropyS: 10.6},
	"UA/A.": {EnthalpyH: -5.7, EntropyS: -16.1},
	"UA/C.": {EnthalpyH: 0, EntropyS: 0},
	"UA/G.": {EnthalpyH: -5.7, EntropyS: -16.1},
	"UA/U.": {EnthalpyH: 0, EntropyS: 0},
	"UC/.A": {EnthalpyH: 0, EntropyS: 0},
	"UC/.C": {EnthalpyH: 0, EntropyS: 0},
	"UC/.G": {EnthalpyH: -1.4, EntropyS: -4.2},
	"UC/.U": {EnthalpyH: 0, EntropyS: 0},
	"UC/A.": {EnthalpyH: -0.7, EntropyS: -1.9},
	"UC/C.": {EnthalpyH: 0, EntropyS: 0},
	"UC/G.": {EnthalpyH: -0.7, EntropyS: -1.9},
	"UC/U.": {EnthalpyH: 0, EntropyS: 0},
	"UG/.A": {EnthalpyH: 0, EntropyS: 0},
	"UG/.C": {EnthalpyH: -0.4, EntropyS: -1.3},
	"UG/.G": {EnthalpyH: 0, EntropyS: 0},
	"UG/.U": {EnthalpyH: 3.1, EntropyS: 10.6},
	"UG/A.": {EnthalpyH: -5.8, EntropyS: -16.4},
	"UG/C.": {EnthalpyH: 0, EntropyS: 0},
	"UG/G.": {EnthalpyH: -5.8, EntropyS: -16.4},
	"UG/U.": {EnthalpyH: 0, EntropyS: 0},
	"UU/.A": {EnthalpyH: 0.6, EntropyS: 2.6},
	"UU/.C": {EnthalpyH: 0, EntropyS: 0},
	"UU/.G": {EnthalpyH: 0.6, EntropyS: 2.6},
	"UU/.U": {EnthalpyH: 0, EntropyS: 0},
	"UU/A.": {EnthalpyH: -2.2, EntropyS: -6.8},
	"UU/C.": {EnthalpyH: 0, EntropyS: 0},
	"UU/G.": {EnthalpyH: -2.2, EntropyS: -6.8},
	"UU/U.": {EnthalpyH: 0, EntropyS: 0},
}

var rnaInternalLoops = loopEnergy{
	1:  {0.0, 0.0},
	2:  {0.0, 0.0},
	3:  {0.0, 0.0},
	4:  {-7.2, -26.8},
	5:  {-6.8, -28.4},
	6:  {-1.3, -10.6},
	7:  {-1.3, -11.0},
	8:  {-1.3, -11.6},
	9:  {-1.3, -11.9},
	10: {-1.3, -12.3},
	11: {-1.3, -12.6},
	12: {-1.3, -12.9},
	13: {-1.3, -13.2},
	14: {-1.3, -13.5},
	15: {-1.3, -13.5},
	16: {-1.3, -13.9},
	17: {-1.3, -14.2},
	18: {-1.3, -14.2},
	19: {-1.3, -14.5},
	20: {-1.3, -14.8},
	21: {-1.3, -14.8},
	22: {-1.3, -15.2},
	23: {-1.3, -15.2},
	24: {-1.3, -15.5},
	25: {-1.3, -15.5},
	26: {-1.3, -15.5},
	27: {-1.3, -15.8},
	28: {-1.3, -15.8},
	29: {-1.3, -16.1},
	30: {-1.3, -16.1},
}

var rnaBulgeLoops = loopEnergy{
	1:  {10.6, 21.9},
	2:  {7.1, 13.9},
	3:  {7.1, 12.6},
	4:  {7.1, 11.3},
	5:  {7.1, 10.0},
	6:  {7.1, 8.7},
	7:  {7.1, 8.1},
	8:  {7.1, 7.7},
	9:  {7.1, 7.4},
	10: {7.1, 7.1},
	11: {7.1, 6.8},
	12: {7.1, 6.4},
	13: {7.1, 6.1},
	14: {7.1, 5.8},
	15: {7.1, 5.5},
	16: {7.1, 5.5},
	17: {7.1, 5.2},
	18: {7.1, 5.2},
	19: {7.1, 4.8},
	20: {7.1, 4.5},
	21: {7.1, 4.5},
	22: {7.1, 4.2},
	23: {7.1, 4.2},
	24: {7.1, 4.2},
	25: {7.1, 3.9},
	26: {7.1, 3.9},
	27: {7.1, 3.5},
	28: {7.1, 3.5},
	29: {7.1, 3.5},
	30: {7.1, 3.2},
}

var rnaHairpinLoops = loopEnergy{
	1:  {0.0, 0.0},
	2:  {0.0, 0.0},
	3:  {1.3, -13.2},
	4:  {4.8, -2.6},
	5:  {3.6, -6.8},
	6:  {-2.9, -26.8},
	7:  {1.3, -15.2},
	8:  {-2.9, -27.1},
	9:  {5.0, -4.5},
	10: {5.0, -4.8},
	11: {5.0, -5.2},
	12: {5.0, -5.5},
	13: {5.0, -5.8},
	14: {5.0, -6.1},
	15: {5.0, -6.1},
	16: {5.0, -6.4},
	17: {5.0, -6.8},
	18: {5.0, -6.8},
	19: {5.0, -7.1},
	20: {5.0, -7.1},
	21: {5.0, -7.4},
	22: {5.0, -7.4},
	23: {5.0, -7.7},
	24: {5.0, -7.7},
	25: {5.0, -8.1},
	26: {5.0, -8.1},
	27: {5.0, -8.1},
	28: {5.0, -8.4},
	29: {5.0, -8.4},
	30: {5.0, -8.7},
}

var rnaEnergies = energies{
	bulgeLoops:         rnaBulgeLoops,
	complement:         rnaComplement,
	danglingEnds:       rnaDanglingEnds,
	hairpinLoops:       rnaHairpinLoops,
	multibranch:        rnaMultibranch,
	internalLoops:      rnaInternalLoops,
	internalMismatches: rnaInternalMismatches,
	nearestNeighbors:   rnaNearestNeighbors,
	terminalMismatches: rnaTerminalMismatches,
	triTetraLoops:      nil,
}
