package pcr

import (
	"fmt"
)

func ExampleDesignPrimersWithOverhangs() {
	tfoX := "aataattacaccgagataacacatcatggataaaccgatactcaaagattctatgaagctatttgaggcacttggtacgatcaagtcgcgctcaatgtttggtggcttcggacttttcgctgatgaaacgatgtttgcactggttgtgaatgatcaacttcacatacgagcagaccagcaaacttcatctaacttcgagaagcaagggctaaaaccgtacgtttataaaaagcgtggttttccagtcgttactaagtactacgcgatttccgacgacttgtgggaatccagtgaacgcttgatagaagtagcgaagaagtcgttagaacaagccaatttggaaaaaaagcaacaggcaagtagtaagcccgacaggttgaaagacctgcctaacttacgactagcgactgaacgaatgcttaagaaagctggtataaaatcagttgaacaacttgaagagaaaggtgcattgaatgcttacaaagcgatacgtgactctcactccgcaaaagtaagtattgagctactctgggctttagaaggagcgataaacggcacgcactggagcgtcgttcctcaatctcgcagagaagagctggaaaatgcgctttcttaa"
	forwardOverhang := "TTATAGGTCTCATACT"
	reverseOverhang := "ATGAAGAGACCATATA"
	fwd, rev := DesignPrimersWithOverhangs(tfoX, forwardOverhang, reverseOverhang, 55.0)

	fmt.Printf("%s, %s", fwd, rev)
	// Output: TTATAGGTCTCATACTAATAATTACACCGAGATAACACATCATGG, TATATGGTCTCTTCATTTAAGAAAGCGCATTTTCCAGC
}

func ExampleDesignPrimers() {
	tfoX := "aataattacaccgagataacacatcatggataaaccgatactcaaagattctatgaagctatttgaggcacttggtacgatcaagtcgcgctcaatgtttggtggcttcggacttttcgctgatgaaacgatgtttgcactggttgtgaatgatcaacttcacatacgagcagaccagcaaacttcatctaacttcgagaagcaagggctaaaaccgtacgtttataaaaagcgtggttttccagtcgttactaagtactacgcgatttccgacgacttgtgggaatccagtgaacgcttgatagaagtagcgaagaagtcgttagaacaagccaatttggaaaaaaagcaacaggcaagtagtaagcccgacaggttgaaagacctgcctaacttacgactagcgactgaacgaatgcttaagaaagctggtataaaatcagttgaacaacttgaagagaaaggtgcattgaatgcttacaaagcgatacgtgactctcactccgcaaaagtaagtattgagctactctgggctttagaaggagcgataaacggcacgcactggagcgtcgttcctcaatctcgcagagaagagctggaaaatgcgctttcttaa"
	fwd, rev := DesignPrimers(tfoX, 55.0)

	fmt.Printf("%s, %s", fwd, rev)
	// Output: AATAATTACACCGAGATAACACATCATGG, TTAAGAAAGCGCATTTTCCAGC
}

func ExampleSimulate() {
	tfoX := "aataattacaccgagataacacatcatggataaaccgatactcaaagattctatgaagctatttgaggcacttggtacgatcaagtcgcgctcaatgtttggtggcttcggacttttcgctgatgaaacgatgtttgcactggttgtgaatgatcaacttcacatacgagcagaccagcaaacttcatctaacttcgagaagcaagggctaaaaccgtacgtttataaaaagcgtggttttccagtcgttactaagtactacgcgatttccgacgacttgtgggaatccagtgaacgcttgatagaagtagcgaagaagtcgttagaacaagccaatttggaaaaaaagcaacaggcaagtagtaagcccgacaggttgaaagacctgcctaacttacgactagcgactgaacgaatgcttaagaaagctggtataaaatcagttgaacaacttgaagagaaaggtgcattgaatgcttacaaagcgatacgtgactctcactccgcaaaagtaagtattgagctactctgggctttagaaggagcgataaacggcacgcactggagcgtcgttcctcaatctcgcagagaagagctggaaaatgcgctttcttaa"
	primers := []string{"TTATAGGTCTCATACTAATAATTACACCGAGATAACACATCATGG", "TATATGGTCTCTTCATTTAAGAAAGCGCATTTTCCAGC"}
	fragments := Simulate(tfoX, 55.0, false, primers)

	fmt.Println(fragments)
	// Output: [TTATAGGTCTCATACTAATAATTACACCGAGATAACACATCATGGATAAACCGATACTCAAAGATTCTATGAAGCTATTTGAGGCACTTGGTACGATCAAGTCGCGCTCAATGTTTGGTGGCTTCGGACTTTTCGCTGATGAAACGATGTTTGCACTGGTTGTGAATGATCAACTTCACATACGAGCAGACCAGCAAACTTCATCTAACTTCGAGAAGCAAGGGCTAAAACCGTACGTTTATAAAAAGCGTGGTTTTCCAGTCGTTACTAAGTACTACGCGATTTCCGACGACTTGTGGGAATCCAGTGAACGCTTGATAGAAGTAGCGAAGAAGTCGTTAGAACAAGCCAATTTGGAAAAAAAGCAACAGGCAAGTAGTAAGCCCGACAGGTTGAAAGACCTGCCTAACTTACGACTAGCGACTGAACGAATGCTTAAGAAAGCTGGTATAAAATCAGTTGAACAACTTGAAGAGAAAGGTGCATTGAATGCTTACAAAGCGATACGTGACTCTCACTCCGCAAAAGTAAGTATTGAGCTACTCTGGGCTTTAGAAGGAGCGATAAACGGCACGCACTGGAGCGTCGTTCCTCAATCTCGCAGAGAAGAGCTGGAAAATGCGCTTTCTTAAATGAAGAGACCATATA]
}

func ExampleDesignAllPossiblePrimers() {
	pht43 := "aagattacaccgagataagcgccacatcatggataaaccgatactcaaagattctatgaagctatttgaggcacttggtacgatcaagtcgcgctcaatgtttggtggcttcggacttttcgctgatgaaacgatgtttgcactggttgtgaatgatcaacttcacatacgagcagaccagcaaacttcatctaacttcgagaagcaagggctaaaaccgtacgtttataaaaagcgtggttttccagtcgttactaagtactacgcgatttccgacgacttgtgggaatccagtgaacgcttgatagaagtagcgaagaagtcgttagaacaagccaatttggaaaaaaagcaacaggcaagtagtaagcccgacaggttgaaagacctgcctaacttacgactagcgactgaacgaatgcttaagaaagctggtataaaatcagttgaacaacttgaagagaaaggtgcattgaatgcttacaaagcgatacgtgactctcactccgcaaaagtaagtattgagctactctgggctttagaaggagcgataaacggcacgcactggagcgtcgttcctcaatctcgcagagaagagctggaaaatgcgctttcttaa"
	allPossiblePairs := DesignAllPossiblePrimers(pht43, 0.4, 0.6, 0.50, 0.60, 18, 30, 5)

	fmt.Println(allPossiblePairs)
	// Output: [{AAGATTACACCGAGATAAGCG TTAAGAAAGCGCATTTTCCAGC} {AAGATTACACCGAGATAAGCG TTAAGAAAGCGCATTTTCCAGCTC} {AAGATTACACCGAGATAAGCGC TTAAGAAAGCGCATTTTCCAGC} {AAGATTACACCGAGATAAGCGC TTAAGAAAGCGCATTTTCCAGCTC} {AAGATTACACCGAGATAAGCGC TTAAGAAAGCGCATTTTCCAGCTCT} {AAGATTACACCGAGATAAGCGC TTAAGAAAGCGCATTTTCCAGCTCTTC} {AAGATTACACCGAGATAAGCGCC TTAAGAAAGCGCATTTTCCAGC} {AAGATTACACCGAGATAAGCGCC TTAAGAAAGCGCATTTTCCAGCTC} {AAGATTACACCGAGATAAGCGCC TTAAGAAAGCGCATTTTCCAGCTCT} {AAGATTACACCGAGATAAGCGCC TTAAGAAAGCGCATTTTCCAGCTCTTC} {AAGATTACACCGAGATAAGCGCCA TTAAGAAAGCGCATTTTCCAGC} {AAGATTACACCGAGATAAGCGCCA TTAAGAAAGCGCATTTTCCAGCTC} {AAGATTACACCGAGATAAGCGCCA TTAAGAAAGCGCATTTTCCAGCTCT} {AAGATTACACCGAGATAAGCGCCA TTAAGAAAGCGCATTTTCCAGCTCTTC} {AAGATTACACCGAGATAAGCGCCAC TTAAGAAAGCGCATTTTCCAGC} {AAGATTACACCGAGATAAGCGCCAC TTAAGAAAGCGCATTTTCCAGCTC} {AAGATTACACCGAGATAAGCGCCAC TTAAGAAAGCGCATTTTCCAGCTCT} {AAGATTACACCGAGATAAGCGCCAC TTAAGAAAGCGCATTTTCCAGCTCTTC}]
}
