package linearfold

import (
	"fmt"
	"testing"
)

func ExampleCONTRAFoldV2() {

	result, score := CONTRAfoldV2("UGAGUUCUCGAUCUCUAAAAUCG")

	fmt.Println(fmt.Sprintf("result: %v , score: %v", result, score))
	// Output: result: ....................... , score: -0.22376699999999988
}

func ExampleViennaRNAFold() {
	result, score := ViennaRNAFold("UCUAGACUUUUCGAUAUCGCGAAAAAAAAU", DefaultTemperature, DefaultEnergyParamsSet)
	fmt.Println(fmt.Sprintf("result: %v , score: %.2f", result, score))
	// Output: result: .......((((((......))))))..... , score: -3.90
}

func TestLinearFold(t *testing.T) {
	sequence := "UGAGUUCUCGAUCUCUAAAAUCG"
	expectedStructure := "......................."
	expectedScore := -0.22376699999999988
	CONTRAfoldV2Test(sequence, expectedStructure, expectedScore, t)

	sequence = "AAAACGGUCCUUAUCAGGACCAAACA"
	expectedStructure = ".....((((((....))))))....."
	expectedScore = 4.90842861201
	CONTRAfoldV2Test(sequence, expectedStructure, expectedScore, t)

	sequence = "AUUCUUGCUUCAACAGUGUUUGAACGGAAU"
	expectedStructure = ".............................."
	expectedScore = -0.2918699999999998
	CONTRAfoldV2Test(sequence, expectedStructure, expectedScore, t)

	sequence = "UCGGCCACAAACACACAAUCUACUGUUGGUCGA"
	expectedStructure = "(((((((...................)))))))"
	expectedScore = 0.9879274133299999
	CONTRAfoldV2Test(sequence, expectedStructure, expectedScore, t)

	sequence = "GUUUUUAUCUUACACACGCUUGUGUAAGAUAGUUA"
	expectedStructure = ".....(((((((((((....)))))))))))...."
	expectedScore = 6.660038360289999
	CONTRAfoldV2Test(sequence, expectedStructure, expectedScore, t)

	sequence = "GGGCUCGUAGAUCAGCGGUAGAUCGCUUCCUUCGCAAGGAAGCCCUGGGUUCAAAUCCCAGCGAGUCCACCA"
	expectedStructure = "(((((((..((((.......))))(((((((.....))))))).(((((.......))))))))))))...."
	expectedScore = 13.974768784808
	CONTRAfoldV2Test(sequence, expectedStructure, expectedScore, t)
}

func CONTRAfoldV2Test(sequence, expectedStructure string, expectedScore float64, t *testing.T) {
	result, score := CONTRAfoldV2(sequence)
	if result != expectedStructure || score != expectedScore {
		t.Errorf("Failed to fold %v. Expected 'result: %v , score: %v', \ngot result: %v , score: %v", sequence, expectedStructure, expectedScore, result, score)
	}
}

func ViennaRNAFoldTest(sequence, expectedStructure string, expectedScore float64, t *testing.T) {
	result, score := ViennaRNAFold(sequence, DefaultTemperature, DefaultEnergyParamsSet)
	if result != expectedStructure || score != expectedScore {
		t.Errorf("Failed to fold %v. Expected 'result: %v , score: %v', \ngot result: %v , score: %v", sequence, expectedStructure, expectedScore, result, score)
	}
}

func BenchmarkViennaRNAFold(b *testing.B) {
	// Run linearfold on a 2915bp sequence
	for n := 0; n < b.N; n++ {
		ViennaRNAFold("GGUCAAGAUGGUAAGGGCCCACGGUGGAUGCCUCGGCACCCGAGCCGAUGAAGGACGUGGCUACCUGCGAUAAGCCAGGGGGAGCCGGUAGCGGGCGUGGAUCCCUGGAUGUCCGAAUGGGGGAACCCGGCCGGCGGGAACGCCGGUCACCGCGCUUUUGCGCGGGGGGAACCUGGGGAACUGAAACAUCUCAGUACCCAGAGGAGAGGAAAGAGAAAUCGACUCCCUGAGUAGCGGCGAGCGAAAGGGGACCAGCCUAAACCGUCCGGCUUGUCCGGGCGGGGUCGUGGGGCCCUCGGACACCGAAUCCCCAGCCUAGCCGAAGCUGUUGGGAAGCAGCGCCAGAGAGGGUGAAAGCCCCGUAGGCGAAAGGUGGGGGGAUAGGUGAGGGUACCCGAGUACCCCGUGGUUCGUGGAGCCAUGGGGGAAUCUGGGCGGACCACCGGCCUAAGGCUAAGUACUCCGGGUGACCGAUAGCGCACCAGUACCGUGAGGGAAAGGUGAAAAGAACCCCGGGAGGGAGUGAAAUAGAGCCUGAAACCGUGGGCUUACAAGCAGUCACGGCCCCGCAAGGGGUUGUGGCGUGCCUAUUGAAGCAUGAGCCGGCGACUCACGGUCGUGGGCGAGCUUAAGCCGUUGAGGCGGAGGCGUAGGGAAACCGAGUCCGAACAGGGCGCAAGCGGGCCGCACGCGGCCCGCAAAGUCCGCGGCCGUGGACCCGAAACCGGGCGAGCUAGCCCUGGCCAGGGUGAAGCUGGGGUGAGACCCAGUGGAGGCCCGAACCGGUGGGGGAUGCAAACCCCUCGGAUGAGCUGGGGCUAGGAGUGAAAAGCUAACCGAGCCCGGAGAUAGCUGGUUCUCCCCGAAAUGACUUUAGGGUCAGCCUCAGGCGCUGACUGGGGCCUGUAGAGCACUGAUAGGGCUAGGGGGCCCACCAGCCUACCAAACCCUGUCAAACUCCGAAGGGUCCCAGGUGGAGCCUGGGAGUGAGGGCGCGAGCGAUAACGUCCGCGUCCGAGCGCGGGAACAACCGAGACCGCCAGCUAAGGCCCCCAAGUCUGGGCUAAGUGGUAAAGGAUGUGGCGCCGCGAAGACAGCCAGGAGGUUGGCUUAGAAGCAGCCAUCCUUUAAAGAGUGCGUAAUAGCUCACUGGUCGAGUGGCGCCGCGCCGAAAAUGAUGCGGGGCUUAAGCCCAGCGCCGAAGCUGCGGGUCUGGGGGAUGACCCCAGGCGGUAGGGGAGCGUUCCCGAUGCCGAUGAAGGCCGACCCGCGAGGCGGCUGGAGGUAAGGGAAGUGCGAAUGCCGGCAUGAGUAACGAUAAAGAGGGUGAGAAUCCCUCUCGCCGUAAGCCCAAGGGUUCCUACGCAAUGGUCGUCAGCGUAGGGUUAGGCGGGACCUAAGGUGAAGCCGAAAGGCGUAGCCGAAGGGCAGCCGGUUAAUAUUCCGGCCCUUCCCGCAGGUGCGAUGGGGGGACGCUCUAGGCUAGGGGGACCGGAGCCAUGGACGAGCCCGGCCAGAAGCGCAGGGUGGGAGGUAGGCAAAUCCGCCUCCCAACAAGCUCUGCGUGGUGGGGAAGCCCGUACGGGUGACAACCCCCCGAAGCCAGGGAGCCAAGAAAAGCCUCUAAGCACAACCUGCGGGAACCCGUACCGCAAACCGACACAGGUGGGCGGGUGCAAGAGCACUCAGGCGCGCGGGAGAACCCUCGCCAAGGAACUCUGCAAGUUGGCCCCGUAACUUCGGGAGAAGGGGUGCUCCCUGGGGUGAUGAGCCCCGGGGAGCCGCAGUGAACAGGCUCUGGCGACUGUUUACCAAAAACACAGCUCUCUGCGAACUCGUAAGAGGAGGUAUAGGGAGCGACGCUUGCCCGGUGCCGGAAGGUCAAGGGGAGGGGUGCAAGCCCCGAACCGAAGCCCCGGUGAACGGCGGCCGUAACUAUAACGGUCCUAAGGUAGCGAAAUUCCUUGUCGGGUAAGUUCCGACCUGCACGAAAAGCGUAACGACCGGAGCGCUGUCUCGGCGAGGGACCCGGUGAAAUUGAACUGGCCGUGAAGAUGCGGCCUACCCGUGGCAGGACGAAAAGACCCCGUGGAGCUUUACUGCAGCCUGGUGUUGGCUCUUGGUCGCGCCUGCGUAGGAUAGGUGGGAGCCUGUGAACCCCCGCCUCCGGGUGGGGGGGAGGCGCCGGUGAAAUACCACCCUGGCGCGGCUGGGGGCCUAACCCUCGGAUGGGGGGACAGCGCUUGGCGGGCAGUUUGACUGGGGCGGUCGCCUCCUAAAAGGUAACGGAGGCGCCCAAAGGUCCCCUCAGGCGGGACGGAAAUCCGCCGGAGAGCGCAAGGGUAGAAGGGGGCCUGACUGCGAGGCCUGCAAGCCGAGCAGGGGCGAAAGCCGGGCCUAGUGAACCGGUGGUCCCGUGUGGAAGGGCCAUCGAUCAACGGAUAAAAGUUACCCCGGGGAUAACAGGCUGAUCUCCCCCGAGCGUCCACAGCGGCGGGGAGGUUUGGCACCUCGAUGUCGGCUCGUCGCAUCCUGGGGCUGAAGAAGGUCCCAAGGGUUGGGCUGUUCGCCCAUUAAAGCGGCACGCGAGCUGGGUUCAGAACGUCGUGAGACAGUUCGGUCUCUAUCCGCCACGGGCGCAGGAGGCUUGAGGGGGGCUCUUCCUAGUACGAGAGGACCGGAAGGGACGCACCUCUGGUUUCCCAGCUGUCCCUCCAGGGGCAUAAGCUGGGUAGCCAUGUGCGGAAGGGAUAACCGCUGAAAGCAUCUAAGCGGGAAGCCCGCCCCAAGAUGAGGCCUCCCACGGCGUCAAGCCGGUAAGGACCCGGGAAGACCACCCGGUGGAUGGGCCGGGGGUGUAAGCGCCGCGAGGCGUUGAGCCGACCGGUCCCAAUCGUCCGAGGUCUUGACCCCUC", DefaultTemperature, DefaultEnergyParamsSet)
	}
}
