name: Blocking Issues

on: 
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened]
  pull_request_target: 
    types: [opened, edited, closed, reopened]
    
jobs: 
  blocking_issues: 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Checks for blocking issues
    steps: 
      - uses: Levi-Lesches/blocking-issues@v2
