name: notify social media

on:
  release: 
  issues: 
  pull_request:
  issue_comment: 
  pull_request_review:
  pull_request_review_comment: 
  discussion: 
  discussion_comment:
  push:
    branches:
      - notify # for testing purposes
      - dev
      - prime
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Actions for Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2